#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     DriveL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DriveR,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "TeleOp_functions.h"

tMotor DRIVEMOTORS[] = { DriveL, DriveR };

task main() {
	waitForStart();
	while (true) {
		getJoystickSettings(joystick);
		arcade_drive(DRIVEMOTORS, 2);
	}


}
