#pragma config(Sensor, S1,     IR,             sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// get_ir_data.c
//
// Copyright (c) 2015 Suit Bots 4628
//

#include "autonomous_functions.h"

float mean(int *data, int dataSize) {
	int avg;
	for (int i = 0; i < dataSize; ++i)
		avg += data[i];
	avg /= dataSize;
	return avg;
}

#define sampleSize 100

int getData(char IR) {
	int populationData[sampleSize];
	eraseDisplay();
	nxtDisplayCenteredBigTextLine(1, "LOADING...");
	for (int i = 0; i < sampleSize; ++i) {
		populationData[i] = IRSensorRegion(IR, false);
		writeDebugStreamLine("%i", IRSensorRegion(IR, false));
		wait1Msec(30);
	}
	return mean(populationData, sampleSize);
}

void readout() {
	if (nNxtButtonPressed == 2) {
		int direction = getData(IR);
		eraseDisplay();
		nxtDisplayCenteredTextLine(1, "Direction: %f", direction);
	}
}

task main()
{
	eraseDisplay();
	while (true) {
		readout();
	}


}
