#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LIFT,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     LEFT_DRIVE,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     RIGHT_DRIVE,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    TUBE_MAN_B,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    TUBE_MAN_FL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    TUBE_MAN_FR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    BALL_DUMP,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "autonomous_functions.h"

tMotor DRIVE_MOTORS[] = { LEFT_DRIVE, RIGHT_DRIVE };

void initialize_robot() {
	servo[TUBE_MAN_B] = 255;
}

int *parseArduinoData(tSensors board) {
	int packet[] = { 0, 0 };
	return packet;
}

int drive_off_ramp_with_IR() {
	return 0;
}

void stopMotors(tMotor *DriveMotors) {
	int size = sizeof(DriveMotors) / sizeof(tMotor);
	for (int i = 0; i < size; ++i) {
		motor[DriveMotors[i]] = 0;
	}
}

void forwardTime(int distance, tMotor *DriveMotors) {
	const int TIME_TO_INCHES = 5;
	int size = sizeof(DriveMotors)/sizeof(tMotor);
	for (int i = 0; i < size; ++i) {
		motor[DriveMotors[i]] = 100;
	}
	wait10Msec(distance * TIME_TO_INCHES);
	stopMotors(DriveMotors);
}

void forwardSlowTime(int distance, tMotor *DriveMotors) {
	const int TIME_TO_INCHES = 5;
	int size = sizeof(DriveMotors)/sizeof(tMotor);
	for (int i = 0; i < size; ++i) {
		motor[DriveMotors[i]] = 30;
	}
	wait10Msec(distance * TIME_TO_INCHES);
	stopMotors(DriveMotors);
}

void backwardTime(int distance, tMotor *DriveMotors) {
	const int TIME_TO_INCHES = 5;
	int size = sizeof(DriveMotors)/sizeof(tMotor);
	for (int i = 0; i < size; ++i) {
		motor[DriveMotors[i]] = -100;
	}
	wait10Msec(distance * TIME_TO_INCHES);
	stopMotors(DriveMotors);
}

void leftTime(int distance, tMotor *DriveMotors) {
	const int TIME_TO_INCHES = 2;
	int size = sizeof(DriveMotors)/sizeof(tMotor);
	for (int i = 0; i < size; ++i) {
		if (i % 2 == 1) {
			motor[DriveMotors[i]] = -100;
		} else {
			motor[DriveMotors[i]] = 100;
		}
	}
	wait10Msec(distance * TIME_TO_INCHES);
	stopMotors(DriveMotors);
}

void rightTime(int distance, tMotor *DriveMotors) {
	const int TIME_TO_INCHES = 2;
	int size = sizeof(DriveMotors)/sizeof(tMotor);
	for (int i = 0; i < size; ++i) {
		if (i % 2 == 1) {
			motor[DriveMotors[i]] = 100;
		} else {
			motor[DriveMotors[i]] = -100;
		}
	}
	wait10Msec(distance * TIME_TO_INCHES);
	stopMotors(DriveMotors);
}

bool grab_tube(bool tubemanState) {
	servo[TUBE_MAN_B] = tubemanState ? 20 : 255;
	wait10Msec(100);
	tubemanState = tubemanState ? false : true;
	return tubemanState;
}

task main()
{
	waitForStart();
	backwardTime(90, DRIVE_MOTORS);
	grab_tube(true);
	forwardTime(100, DRIVE_MOTORS);


}
