#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     SPINNY,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LIFT,          tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     LEFT_DRIVE,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     RIGHT_DRIVE,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    TUBE_MAN_B,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    TUBE_MAN_FL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    TUBE_MAN_FR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    BALL_DUMP,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "TeleOp_functions.h"

//const int MAX_JOY_VALUE = 255;
//const int MIN_JOY_VALUE = -MAX_JOY_VALUE;

tMotor DRIVEMOTORS[] = { LEFT_DRIVE, RIGHT_DRIVE };


void initializeRobot() {
	servo[TUBE_MAN_B] = 0;
	servo[TUBE_MAN_FL] = 0;
	servo[TUBE_MAN_FR] = 0;
	servo[BALL_DUMP] = 0;
}

// bottom left joystick

void drive(int jx, int jy) {
	const int left = jy + jx;
	const int right = jy - jx;

	motor[LEFT_DRIVE] = left;
	motor[RIGHT_DRIVE] = right;
}

// Y button
void tube_man_back() {
	if (joy2Btn(01)) {
		servo[TUBE_MAN_B] = 255;
	}
	else if (joy2Btn(02)) {
		servo[TUBE_MAN_B] = 0; //A Button
	}
}

void tube_man_front() {
	if (joy2Btn(03)) {
		servo[TUBE_MAN_FL] = 255;
		servo[TUBE_MAN_FR] = 255;
	}
	else if (joy2Btn(04)) {
		servo[TUBE_MAN_FL] = 0;
		servo[TUBE_MAN_FR] = 0;
	}
}

void drop_balls() {
	if (joy2Btn(05)) {
		servo[BALL_DUMP] = 70;
	}
	if (joy2Btn(06)) {
		servo[BALL_DUMP] = 255;
	}
}

// right joystick
void lift_op() {
	operate_Lift(LIFT);
}

//// right trigger down
//void scoop_tilt_back () { // this is the scoop dumping backwards
//	if (joy2Btn(03)) {
//		servo[SCOOP_TILT] = 80;
//	}
//}

//// right trigger up
//void scoop_tilt_fwd () { // this is the scoop tilting forward
//	if (joy2Btn(04)) {
//		servo[SCOOP_TILT] = 0;
//	}
//}



void handleDriving() {
	arcade_drive(DRIVEMOTORS, 2);
}

task main()
{
	initializeRobot ();
	waitForStart ();

	while (true) {
		getJoystickSettings(joystick);
		handleDriving();
		lift_op();
		tube_man_back();
		drop_balls();
		tube_man_front();
		operate_Spinny(SPINNY);
		//

		scoop_tilt_back();
		//scoop_tilt_fwd();
	}

}
